name: Bug Report
description: File a bug report to help us improve vssh
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: vssh Version
      description: What version of vssh are you running?
      placeholder: "v0.1.5 (run 'vssh version' to check)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (AMD64)
        - Linux (ARM64)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (AMD64)
        - Windows (ARM64)
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: auth_method
    attributes:
      label: Vault Authentication Method
      description: Which authentication method are you using?
      options:
        - Token
        - Username/Password
        - LDAP
        - OIDC
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter credentials '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug Output
      description: Please run the command with `--debug` flag and paste the output here.
      placeholder: |
        Run: vssh --debug user@server.com
        Paste the output here (remove any sensitive information like tokens or passwords)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your vssh configuration (remove sensitive information)
      placeholder: |
        Contents of ~/.config/vssh/config.yaml (remove sensitive values like addresses, usernames, etc.)
      render: yaml

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - Go version (if building from source): 
        - Vault server version: 
        - SSH client version: 
        - Any relevant network/firewall information:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Screenshots, error messages, related issues, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have removed sensitive information from logs and configuration
          required: true
        - label: I have tested with the latest version of vssh
          required: true
