name: Feature Request
description: Suggest an idea for vssh
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature request fall into?
      options:
        - Authentication (new auth methods, token handling)
        - SSH Integration (new SSH options, compatibility)
        - Certificate Management (signing, validation, caching)
        - Configuration (new config options, validation)
        - CLI/UX (command line interface, user experience)
        - Documentation (guides, examples, help text)
        - Performance (speed, efficiency improvements)
        - Security (security enhancements, hardening)
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        How would you use this feature? What workflow would it enable?
        Example scenarios where this would be helpful.
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      placeholder: |
        Command examples, configuration examples, or workflow examples.
        Show what the user experience would look like.
      render: shell

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would be helpful)
        - High (important for my workflow)
        - Critical (blocking my use of vssh)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change, minimal impact)
        - Medium (moderate change, some new code)
        - Complex (significant change, new architecture)
        - Unknown (not sure about implementation)

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        If you have technical knowledge, share your thoughts on implementation.
        This is optional but can be helpful for planning.

  - type: textarea
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      placeholder: |
        Would this change existing behavior or require configuration changes?
        How could we maintain backward compatibility?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Links to similar features in other tools, screenshots, mockups, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have considered if this could be solved with existing features
          required: true
        - label: This feature would benefit other users, not just my specific use case
          required: true
